rem Install prerequisites...
echo Installing prerequisites...
start /wait Engine\Extras\Redist\en-us\UE4PrereqSetup_x64.exe /quiet

rem Register the engine installation...

REG ADD "HKCU\Software\Epic Games\Unreal Engine\Builds" /v "{4.24-custom-prompto}" /t REG_SZ /d "%CD%"